alg: mend
train_base: False
edit_lr: 1e-4
mend:
  one_sided: False
  n_hidden: 1
  hidden_dim: null
  init: id
  norm: False
  combine: True
  x_only: False
  delta_only: False
  act: relu
  rank: 1920
  mlp_class: IDMLP
  shared: True
editable_params:
- model.encoder.layers.4.fc1.weight
- model.encoder.layers.4.fc2.weight
- model.encoder.layers.5.fc1.weight
- model.encoder.layers.5.fc2.weight
- model.decoder.layers.4.fc1.weight
- model.decoder.layers.4.fc2.weight
- model.decoder.layers.5.fc1.weight
- model.decoder.layers.5.fc2.weight